### ISSUE TITLE
Failing to build on Travis with :all

### ISSUE THREAD

**Issue by DannyBen** [pat/combustion#72]
Hi,

Not sure if it is a bug or a configuration error on my part.

**Failing Case**
With this line in my spec_helper:
```
Combustion.initialize! :all
```

The build [fails](https://travis-ci.org/DannyBen/pundit_extra/builds/108111558) on travis with the chief complaint being: 
```
activesupport-4.2.5.1/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- action_mailer/railtie (LoadError)
```

**Passing Case**
However, with this line:

```
Combustion.initialize! :action_controller, :action_view
```

It [succeeds](https://travis-ci.org/DannyBen/pundit_extra/builds/108115340).

In both cases, I did not experience this issue on my local machine (using RVM as well) so I am not sure what to make of it.

**Comment by artofhuman** [comment]
> Combustion is a library to help you test your Rails Engines 

I think you gem is not an engine.

**Comment by DannyBen** [comment]
Do you think that the fact it is not an engine is the cause for it failing on travis and not failing locally?
And why not make Combustion work for any rails gem development project, and not just engines? I mean it looks like its practically working already.

**Comment by pat** [comment]
I use Combustion with non-engine gems (Thinking Sphinx in particular, which has a railtie, but no engine).

I'm not quite sure why, but when bundler is installing gems in the failing build, it uses a _very_ old version of actionmailer - 0.6.1. I'm quite sure railties weren't a thing then (10 years or so ago!). I'd recommend being clear about your runtime dependencies in your gemspec instead of your Gemfile, and anything essential to the gem _working_ should be a runtime dependency, not just a test/development dependency.
